version: '3.8'

services:
  backend:
    image: 537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_backend:latest
    container_name: backend
    env_file:
      - .env.prod
    expose:
      - "5000"
    networks:
      - app-network
    restart: always

  redis:
    image: redis:6
    container_name: redis
    networks:
      - app-network
    restart: always

  nginx:
    image: 537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_frontend:latest
    container_name: nginx-prod
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
