
version: '3.8'

services:
  backend:
    image: 537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  frontend:
    image: 537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:6
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
