name: CI/CD - Staging Deploy (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Nginx + React (staging)
      run: |
        IMAGE_URI=537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_frontend
        docker build -f frontend/Dockerfile.staging -t $IMAGE_URI:staging ./frontend
        docker push $IMAGE_URI:staging

    - name: Build and Push Backend (staging)
      run: |
        IMAGE_URI=537124969361.dkr.ecr.us-west-1.amazonaws.com/smart_parking_backend
        docker build -t $IMAGE_URI:staging ./backend
        docker push $IMAGE_URI:staging

    - name: Deploy to EC2 (staging)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/staging
          docker-compose -f docker-compose-staging.yml pull
          docker-compose -f docker-compose-staging.yml up -d
        EOF
